import os
import pysubs2
import wave

TEMP_DIR = os.getenv("TEMP_DIR", "./temp")
AUDIO_PATH = os.path.join(TEMP_DIR, "narration.wav")
TEXT_PATH = os.path.join(TEMP_DIR, "text.txt")
SUBTITLE_PATH = os.path.join(TEMP_DIR, "subtitles.ass")

def get_audio_duration(audio_path):
    with wave.open(audio_path, "rb") as wav_file:
        frames = wav_file.getnframes()
        rate = wav_file.getframerate()
        duration = frames / float(rate)
    return duration

def generate_subtitles():
    with open(TEXT_PATH, "r") as f:
        lines = [line.strip() for line in f if line.strip()]
    
    total_duration = get_audio_duration(AUDIO_PATH)
    num_lines = len(lines)
    duration_per_line = total_duration / num_lines

    subs = pysubs2.SSAFile()
    subs.info["Title"] = "Generated by MindBloom"

    for idx, line in enumerate(lines):
        start_ms = int(idx * duration_per_line * 1000)
        end_ms = int((idx + 1) * duration_per_line * 1000)

        event = pysubs2.SSAEvent(
            start=start_ms,
            end=end_ms,
            text=line,
            style="Default"
        )
        subs.events.append(event)

    subs.save(SUBTITLE_PATH)
    print(f"[+] Subtitles generated successfully at {SUBTITLE_PATH}!")

if __name__ == "__main__":
    generate_subtitles()

